lib/stormchat_web/router.ex
defmodule StormchatWeb.Router do
  use StormchatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StormchatWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/chats", PageController, :chat

    resources "/locations", LocationController, only: [:index]
    resources "/registration", UserController

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete

  end

  scope "/auth", StormchatWeb do
      pipe_through :browser

      get "/:provider", AuthController, :request
      get "/:provider/callback", AuthController, :callback
  end

  scope "/api/v1", StormchatWeb do
     pipe_through :api

     resources "/posts/:topic", PostController, except: [:new, :edit]
     post "/posts/mobile/:topic", PostController, :mobile

     get "/alerts/:location", PageController, :alert
     get "/alerts/mobile/:location", PageController, :mobile

     post "/new_user", TokenController, :new
     post "/edit_user", TokenController, :edit
     post "/token", TokenController, :create
     delete "/token", TokenController, :delete
  end

end

lib/stormchat_web/templates/page/alert.html.eex
<div class="row">
  <div class="col">
    <h3><%= @id %></h3>
    <script>
      window.gameName = "<%= @id %>";
    </script>
    <div id="react-chat">
      <p>React app not loaded...</p>
    </div>
  </div>
</div>

lib/stormchat_web/templates/page/chat.html.eex
<div class="row">
  <div class="col">

    <div class="card border-dark mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= @event %></h5>
        <h6 class="card-subtitle mb-2 text-muted"> <%= @areaDesc %></h6>
        <p class="card-text limit-text"><%= @instruction %></p>
        <div class="card-block">
          <div class="row">
            <div class="col-md-3">
              <strong> Severity: &nbsp;</strong>
              <%= case @severity do %>
	      <% "Unknown" -> %>
	      <p style="color: blue;" ><%= @severity %></p>
              <% "Severe" -> %>
              <p style="color: red;" ><%= @severity %></p>
              <% "Moderate" ->%>
              <p style="color: orange;" ><%= @severity %></p>
              <% "Minor" ->%>
              <p style="color: green;" ><%= @severity %></p>
              <% end %>
            </div>
            <div class="col-md-3">
              <strong> Certainty: &nbsp;</strong> <p><%= @certainty %></p>
            </div>
            <div class="col-md-3">
              <strong> Category: &nbsp;</strong> <p><%= @category %></p>
            </div>
            <div class="col-md-3">
              <strong> Response: &nbsp;</strong> <p><%= @response %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>

    <script>
    window.current_topic = "<%= @alert_id %>";
    window.current_id = "<%= @user_id %>";
    </script>
    <div id="react-chat">
      <p>React app loading...</p>
    </div>
  </div>
</div>

lib/stormchat_web/templates/page/index.html.eex
<br><h1>Active alerts in <%= @location %></h1><hr>

<%= if @alerts == %{} do %>
  <br><br>
  <h1>** NO ACTIVE ALERTS**</h1>
<% end %>

<%= for {key, alert} <- @alerts do %>
  <div class="card border-dark mb-3">
    <div class="card-body">
      <h5 class="card-title"><%= alert["event"] %></h5>
      <h6 class="card-subtitle mb-2 text-muted"> <%= alert["areaDesc"] %></h6>
      <p class="card-text limit-text"><%= alert["description"] %></p>
      <div class="card-block">
        <div class="row">
          <div class="col-md-3">
            <strong> Severity: &nbsp;</strong>
            <%= case alert["severity"] do %>
            <% "Extreme" -> %>
            <p style="color: red;" ><%= alert["severity"] %></p>
            <% "Severe" -> %>
            <p style="color: orange;" ><%= alert["severity"] %></p>
            <% "Moderate" ->%>
            <p style="color: green;" ><%= alert["severity"] %></p>
            <% "Minor" ->%>
            <p style="color: blue;" ><%= alert["severity"] %></p>
       	    <% "Unknown" ->%>
      	    <p style="color: grey;" ><%= alert["severity"] %></p>
            <% end %>
          </div>
          <div class="col-md-3">
            <strong> Certainty: &nbsp;</strong> <p><%= alert["certainty"] %></p>
          </div>
          <div class="col-md-3">
            <strong> Category: &nbsp;</strong> <p><%= alert["category"] %></p>
          </div>
          <div class="col-md-3">
            <strong> Response: &nbsp;</strong> <p><%= alert["response"] %></p>
          </div>
        </div>
      </div> <br>
      <span><%= link "Talk about this", to: page_path(@conn, :chat , %{id: key}), class: "btn btn-primary btn-lg" %></span>
    </div>
  </div>
<% end %>

lib/stormchat_web/templates/page/index_not_logged.html.eex
<br>
<div class="row">
  <div class="col-md-5">

    <h1>Create an account</h1><hr>

    <%= form_for @changeset, user_path(@conn, :create), fn f -> %>
    <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
    </div>
    <% end %>

    <div class="form-group">
      <label>Name</label>
      <%= text_input f, :name, class: "form-control" %>
      <%= error_tag f, :name %>
    </div>

    <div class="form-group">
      <label>Email</label>
      <%= email_input f, :email, class: "form-control" %>
      <%= error_tag f, :email %>
    </div>

    <div class="form-group">
      <label>Password</label>
      <%= password_input f, :password, class: "form-control" %>
      <%= error_tag f, :password %>
    </div>

    <div class="form-group">
      <label>Location</label><br>
      <%= select f, :location , Enum.map(@locations, &{&1.name, &1.abb}), class: "btn-block"%>
      <%= error_tag f, :location %>
    </div>

    <div class="form-group">
      <label>Subscribe</label><br>
      <%= checkbox f, :subscribed, class: "checkbox" %>
      <%= error_tag f, :subscribed %>
    </div>

    <div class="form-group">
      <%= submit "Register", class: "btn btn-primary btn-block" %>
    </div>
    <% end %>
  </div>


  <div class="col-md-1">
  </div>
  <div class="col-md-1">
    <div style="border-left: 2px solid; height: 100%;" class="text-secondary">
    </div>
  </div>

  <div class="col-md-5">

    <h2>Login</h2><hr>

    <%= form_for @conn, session_path(@conn, :create), [name: :session], fn f -> %>
    <div class="form-group">
      <label>Email</label>
      <%= text_input f, :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Password</label>
      <%= password_input f, :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= submit "Login", class: "btn btn-primary btn-block" %>
    </div>
    <% end %>

  </div>
</div>